### Importação de bibliotecas

In [ ]:
import pandas as pd 
from pathlib import Path
from pandas import DataFrame

### Leitura de arquivos

In [75]:
ano = 2023
path_dicionario = rf'../data/raw/dados_{ano}/DICIONÁRIO/Dicionario_Microdados_AEEB_{ano}.xlsx'
path_dados = rf'../data/raw/dados_{ano}/DADOS/'


def gerar_df_dic(ano: str, nome_tabela: str) -> tuple[DataFrame, DataFrame]:
    """
    Carrega o dataframe de dados e o respectivo dicionário a partir de um ano e do nome da tabela.
    """
    path_dados = rf'../data/raw/dados_{ano}'
    path_alunos = Path(f'{path_dados}/DADOS/{nome_tabela}.csv')
    raw = pd.read_csv(path_alunos, sep=";", encoding="latin-1")
    
    path_dicionario = Path(f'{path_dados}/DICIONÁRIO/Dicionario_Microdados_AEEB_{ano}.xlsx')
    
    print(f"Lendo dicionário em: {path_dicionario}")
    
    dicionario = pd.read_excel(path_dicionario, sheet_name=nome_tabela)   
    dicionario.columns = dicionario.iloc[0].to_list()
    dicionario = dicionario[1:]
    try:
        dicionario.set_index('Variável', inplace=True)
    except:
        print('coluna variavel nao encontrada no dicionario')

    return raw, dicionario

#### TS_ALUNO <br>
> Informações dos alunos que participaram das avaliações estaduais do 2º ano do ensino fundamental.

In [76]:
raw_alunos, dicionario_alunos = gerar_df_dic(2023,'TS_ALUNO')
raw_alunos.head(5)

Lendo dicionário em: ..\data\raw\dados_2023\DICIONÁRIO\Dicionario_Microdados_AEEB_2023.xlsx

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2023,11,RO,11008701,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
1,2023,11,RO,11008695,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,714.314857,0
2,2023,11,RO,11008687,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
3,2023,11,RO,11008682,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,759.206313,1
4,2023,11,RO,11008729,2,60000001,3,1100205,Porto Velho,0,0,19,NaN,NaN,0

In [77]:
dicionario_alunos

,Descrição,Variáveis Categóricas,Tamanho,Tipo
Variável,,,,
NU_ANO_AVALIACAO,Ano de aplicação da avaliação estadual,NaN,4,Numérica
CO_UF,Código da Unidade da Federação,NaN,2,Numérica
SG_UF,Sigla da Unidade da Federação,NaN,2,Alfanumérica
ID_ALUNO,Identificador do Aluno,NaN,8,Numérica
TP_SERIE,Ano Escolar,2 - 2º ano do Ensino Fundamental,1,Numérica
ID_ESCOLA,Máscara do Códigoo da Escola (códigos fictícios),NaN,8,Numérica
TP_DEPENDENCIA,Dependência Administrativa da Escola,1 - Federal;\n2 - Estadual;\n3 - Municipal;\n4...,1,Numérica
CO_MUNICIPIO,Código do Município onde está localizada a esc...,NaN,7,Numérica
NO_MUNICIPIO,Nome do Município onde está localizada a escola.,NaN,150,Alfanumérica
IN_PRESENCA_LP,Indicador de presença na prova de Língua Portu...,0 - Ausente,1,Numérica
NaN,NaN,1 - Presente,NaN,NaN
IN_PREENCHIMENTO_LP,Indicador de preenchimento da prova de Língua ...,0 - Prova não preenchida;\n1 - Prova preenchida,1,Numérica
CO_CADERNO_LP,Código do Caderno atribuído ao aluno na prova ...,NaN,2,Numérica
VL_PESO_ALUNO_LP,Peso do aluno na prova de Língua Portuguesa,NaN,12,Numérica
VL_PROFICIENCIA_LP,Proficiência do aluno em Língua Portuguesa (LP...,NaN,12,Numérica
IN_ALFABETIZADO,"Indica se o aluno, mediante o resultado da ava...",0 - Não;\n1 - Sim.,1,Numérica

#### TS_ITEM <br>
> Informações dos itens de provas utilizados na avaliação estadual do 2º ano do ensino fundamental para a disciplina Língua Portuguesa (LP).

In [71]:
raw_itens, dicionario_itens = gerar_df_dic(2023,'TS_ITEM')
raw_itens.head(5)

Lendo dicionário em: ..\data\raw\dados_2023\DICIONÁRIO\Dicionario_Microdados_AEEB_2023.xlsx

,NU_ANO_AVALIACAO,CO_UF,SG_UF,CO_BLOCO,NU_POSICAO,CO_ITEM,TP_SERIE,TP_DISCIPLINA,NU_DESCRITOR_HABILIDADE,DS_GABARITO,TP_RESPOSTA_ITEM,TP_MODELO_TRI,NU_PARAM_A,NU_PARAM_B,NU_PARAM_C,NU_PARAM_B1,NU_PARAM_B2,NU_PARAM_B3,NU_PARAM_B4,IN_ITEM_COMUM
0,2023,11,RO,3,2,81,2,1,H4,B,3,2,0.06,708.75,0.38,NaN,NaN,NaN,NaN,0
1,2023,11,RO,7,6,69,2,1,H1,A,3,2,0.02,737.60,0.25,NaN,NaN,NaN,NaN,0
2,2023,11,RO,5,8,112,2,1,H9,D,3,2,0.03,728.75,0.15,NaN,NaN,NaN,NaN,0
3,2023,11,RO,7,1,98,2,1,H2,A,3,2,0.04,643.49,0.18,NaN,NaN,NaN,NaN,0
4,2023,11,RO,1,5,109,2,1,H9,D,3,2,0.04,757.80,0.18,NaN,NaN,NaN,NaN,0

In [72]:
dicionario_itens.head(5)

,Descrição,Variáveis Categóricas,Tamanho,Tipo
Variável,,,,
NU_ANO_AVALIACAO,Ano de aplicação da avaliação estadual,NaN,4,Numérica
CO_UF,Código da Unidade da Federação,NaN,2,Numérica
SG_UF,Sigla da Unidade da Federação,NaN,2,Alfanumérica
CO_BLOCO,Código do Bloco,NaN,2,Numérica
NU_POSICAO,Posição do item no Bloco.,NaN,2,Numérica

#### TS_ESTADO

> Resultados das avaliações estaduais por UF do 2º ano do ensino fundamental para a disciplina Língua Portuguesa (LP), equalizadas com o SAEB.

In [78]:
raw_uf, dicionario_uf = gerar_df_dic(2023,'TS_ESTADO')
raw_uf.head(5)

Lendo dicionário em: ..\data\raw\dados_2023\DICIONÁRIO\Dicionario_Microdados_AEEB_2023.xlsx

,NU_ANO_AVALIACAO,CO_UF,SG_UF,TP_SERIE,ID_TIPO_REDE,PC_ALUNO_ALFABETIZADO,VL_MEDIA_LP
0,2023,11,RO,2,2,58.65,751.4731
1,2023,11,RO,2,3,65.17,760.1971
2,2023,11,RO,2,5,64.60,759.4357
3,2023,13,AM,2,3,49.20,733.6637
4,2023,13,AM,2,5,52.20,736.4687

In [79]:
dicionario_uf.head(5)

,Descrição,Variáveis Categóricas,Tamanho,Tipo
Variável,,,,
NU_ANO_AVALIACAO,Ano de aplicação da avaliação estadual,2023,4,Numérica
CO_UF,Código da Unidade da Federação,NaN,2,Numérica
SG_UF,Sigla da Unidade da Federação,NaN,2,Alfanumérica
TP_SERIE,Ano Escolar,2 - 2º ano do Ensino Fundamental,1,Numérica
ID_TIPO_REDE,Rede de ensino avaliada para construção do res...,"0 - Total (Federal, Estadual, Municipal e Pri...",1,Numérica

#### TS_MUNICIPIO 

> Resultados das avaliações estaduais por município do 2º ano do ensino fundamental para a disciplina Língua Portuguesa (LP), equalizadas com o SAEB.

In [80]:
raw_municipio, dicionario_municipio = gerar_df_dic(2023,'TS_MUNICIPIO')
raw_municipio.head(5)

Lendo dicionário em: ..\data\raw\dados_2023\DICIONÁRIO\Dicionario_Microdados_AEEB_2023.xlsx

,NU_ANO_AVALIACAO,CO_UF,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,TP_SERIE,ID_TIPO_REDE,PC_ALUNO_ALFABETIZADO,VL_MEDIA_LP
0,2023,11,RO,1100015,Alta Floresta D'Oeste,2,5,64.55,758.3304
1,2023,11,RO,1100015,Alta Floresta D'Oeste,2,3,64.55,758.3304
2,2023,11,RO,1100023,Ariquemes,2,3,62.30,757.0999
3,2023,11,RO,1100023,Ariquemes,2,5,62.30,757.0999
4,2023,11,RO,1100031,Cabixi,2,5,69.10,767.8763

In [81]:
dicionario_municipio.head(5)

,Descrição,Variáveis Categóricas,Tamanho,Tipo
Variável,,,,
NU_ANO_AVALIACAO,Ano de aplicação da avaliação estadual,NaN,4,Numérica
CO_UF,Código da Unidade da Federação,NaN,2,Numérica
SG_UF,Sigla da Unidade da Federação,NaN,2,Alfanumérica
CO_MUNICIPIO,Código do Município,NaN,7,Numérica
CO_MUNICIPIO,Nome do Município,NaN,150,Alfanumérica

### Analise exploratoria dos dados e Qualidade dos dados

                                0         1         2         3         4
ano                          2023      2023      2023      2023      2023
sigla_uf                       AM        PB        PR        AP        PE
serie                           2         2         2         2         2
rede                            3         2         5         3         5
taxa_alfabetizacao           49.2     55.23     73.12     41.87     58.95
media_portugues          733.6637  744.8152  757.2146  732.7858  747.4522
proporcao_aluno_nivel_0       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_1       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_2       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_3       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_4       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_5       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_6       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_7       NaN       NaN       NaN       NaN       NaN
proporcao_aluno_nivel_8       NaN       NaN       NaN       NaN       NaN

In [8]:
df_raw.shape

(145, 15)

In [6]:
df_raw.isna().sum()

ano                         0
sigla_uf                    0
serie                       0
rede                        0
taxa_alfabetizacao          0
media_portugues             0
proporcao_aluno_nivel_0    70
proporcao_aluno_nivel_1    70
proporcao_aluno_nivel_2    70
proporcao_aluno_nivel_3    70
proporcao_aluno_nivel_4    70
proporcao_aluno_nivel_5    70
proporcao_aluno_nivel_6    70
proporcao_aluno_nivel_7    70
proporcao_aluno_nivel_8    70
dtype: int64